"""Assemble a single self-contained HTML dashboard.

No server and no extra dependency: every chart is embedded as a base64 PNG, so
``reports/dashboard.html`` can be emailed or opened offline and still works.
"""

from __future__ import annotations

import base64
from pathlib import Path

from . import config

CSS = """
:root { --bg:#0f172a; --panel:#1e293b; --ink:#e2e8f0; --muted:#94a3b8;
         --accent:#38bdf8; --good:#34d399; --bad:#f87171; }
* { box-sizing:border-box; }
body { margin:0; font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;
       background:var(--bg); color:var(--ink); }
header { padding:28px 36px 8px; }
h1 { margin:0 0 4px; font-size:26px; }
header p { margin:0; color:var(--muted); }
.kpis { display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr));
        gap:14px; padding:20px 36px; }
.kpi { background:var(--panel); border-radius:12px; padding:16px 18px;
       border:1px solid #334155; }
.kpi .label { color:var(--muted); font-size:12px; text-transform:uppercase;
              letter-spacing:.06em; }
.kpi .value { font-size:24px; font-weight:700; margin-top:6px; }
.kpi .value.good { color:var(--good); }
.kpi .value.bad { color:var(--bad); }
section { padding:8px 36px 24px; }
section h2 { font-size:18px; border-left:4px solid var(--accent);
             padding-left:10px; margin:18px 0 12px; }
.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(420px,1fr));
        gap:20px; }
.card { background:var(--panel); border-radius:12px; padding:14px;
        border:1px solid #334155; }
.card img { width:100%; border-radius:8px; display:block; }
table { width:100%; border-collapse:collapse; font-size:13px; }
th,td { padding:7px 10px; text-align:left; border-bottom:1px solid #334155; }
th { color:var(--muted); text-transform:uppercase; font-size:11px;
     letter-spacing:.05em; }
tr:nth-child(even) td { background:rgba(148,163,184,.06); }
footer { color:var(--muted); font-size:12px; padding:20px 36px 40px; }
"""


def _img(path: Path) -> str:
    data = base64.b64encode(path.read_bytes()).decode("ascii")
    return f'<div class="card"><img alt="{path.stem}" src="data:image/png;base64,{data}"/></div>'


def _fmt(value: float, money: bool = True) -> str:
    return f"${value:,.0f}" if money else f"{value:,.0f}"


def _kpi(label: str, value: str, css: str = "") -> str:
    return f'<div class="kpi"><div class="label">{label}</div><div class="value {css}">{value}</div></div>'


def build_dashboard(
    metrics: dict, kpis: dict, tables: dict, chart_paths: list, output=None
) -> Path:
    """Write the dashboard HTML and return its path."""
    output = output or config.DASHBOARD_FILE

    kpi_html = "".join(
        [
            _kpi("Total orders", _fmt(kpis["total_orders"], money=False)),
            _kpi("Recognised orders", _fmt(kpis["recognised_orders"], money=False)),
            _kpi("Total revenue", _fmt(kpis["total_revenue"])),
            _kpi("Avg. order value", _fmt(kpis["avg_order_value"])),
            _kpi("Units sold", _fmt(kpis["total_units"], money=False)),
            _kpi("Completion rate", f'{kpis["completion_rate"]:.0f}%'),
            _kpi("Customers", _fmt(kpis["customers"], money=False)),
            _kpi("Products", _fmt(kpis["products"], money=False)),
        ]
    )

    sections = []
    section_titles = {
        "products": "Product performance",
        "countries": "Geography",
        "payments": "Payment methods",
        "customers": "Top customers",
        "status": "Order status",
        "segments": "Customer segments (KMeans / RFM)",
        "predictors": "Conversion predictors (ML)",
    }
    for key, title in section_titles.items():
        if key in tables and not tables[key].empty:
            sections.append(f"<h2>{title}</h2>")
            sections.append(
                '<div class="card">'
                + tables[key].to_html(index=False, border=0, float_format=lambda x: f"{x:,.2f}")
                + "</div>"
            )

    charts_html = '<div class="grid">' + "".join(_img(Path(p)) for p in chart_paths) + "</div>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>E-commerce Orders - Analysis Dashboard</title>
<style>{CSS}</style>
</head>
<body>
<header>
  <h1>E-commerce Orders - Analysis Dashboard</h1>
  <p>{metrics['rows_before']} raw rows cleaned to {metrics['rows_after']} orders &middot;
     data-quality score {metrics['score_before']}/10 &rarr; {metrics['score_after']}/10</p>
</header>
<div class="kpis">{kpi_html}</div>
<section>{charts_html}</section>
<section>{''.join(sections)}</section>
<footer>Generated by <code>python -m src.run_analysis</code> &middot;
synthetic demo data &middot; revenue counts only Completed and Shipped orders.</footer>
</body>
</html>
"""
    output.write_text(html, encoding="utf-8")
    return output
